# Generated by Django 5.2 on 2025-05-17 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enclosure',
            name='animal_count',
        ),
    ]
