# Generated by Django 5.2.3 on 2025-06-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_manager', '0002_remove_enclosure_animal_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='enclosure',
        ),
        migrations.AddField(
            model_name='employee',
            name='enclosures',
            field=models.ManyToManyField(blank=True, related_name='employees', to='zoo_manager.enclosure'),
        ),
    ]
