# Generated by Django 5.2.3 on 2025-06-19 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_manager', '0003_remove_employee_enclosure_employee_enclosures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enclosure',
            name='responsible_employee',
        ),
        migrations.AddField(
            model_name='enclosure',
            name='responsible_employees',
            field=models.ManyToManyField(blank=True, related_name='responsible_enclosures', to=settings.AUTH_USER_MODEL),
        ),
    ]
