# Generated by Django 5.2.3 on 2025-06-19 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_manager', '0004_remove_enclosure_responsible_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='enclosure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoo_manager.enclosure'),
        ),
    ]
