# Generated by Django 5.2.3 on 2025-06-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_manager', '0005_task_enclosure'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='health',
            field=models.BooleanField(default=True),
        ),
    ]
